---
language: python
python: "2.7"

env:
  - ANSIBLE_HOST_KEY_CHECKING=False

before_install:
  - sudo apt-get update -qq

install:
  - sudo pip install --upgrade pip
  - sudo pip install ansible

script:
  - "ansible-playbook -i test/inventory zend-server.yml --syntax-check"
  - "ansible-playbook -i test/inventory zend-server.yml -vvvv --connection=local --sudo"
