---
- name: Create my.cnf file.
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644

- name: Restart MySQL server.
  service: name=mysql state=restarted enabled=true
